/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dunn;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;
import java_cup.runtime.Symbol;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 05C4R
 */
public class Dunn extends javax.swing.JFrame {
FileReader file;
      Sintactico asin;
    private Preprocesado preprocesado;
    private algoritmo al = new algoritmo();
    private ArrayList<Objeto> objetos;
    private ArrayList<Grupo> grupos;
    private ArrayList<String> nombreAtributos;
    private DefaultTableModel modelo;
    private File archivoSelecionado;
    private Thread cargando;
    private Thread proceso; 
    private Object datos[] = new Object[2];
    private VisualizaObjetos detalle;
    private ArrayList <Integer> num_instancia;
    private ArrayList <Integer> num_cluster;
                    
    /**
     * Creates new form DunnForm
     */
    public Dunn() {
        initComponents();
        this.setLocationRelativeTo(null);
        preprocesarBoton.setEnabled(false);
        analizarBoton.setEnabled(false);
        modelo = (DefaultTableModel)objetosTabla.getModel();
        detalle=new VisualizaObjetos(this,true);
      FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo arff","arff");      
      selectorArchivo.setFileFilter(filtro);
        
                    
    }
public void limpiarTabla(JTable tabla){
        try {
            DefaultTableModel modelo=(DefaultTableModel) tabla.getModel();
            int filas=tabla.getRowCount();
            for (int i = 0;filas>i; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoSelector = new javax.swing.JDialog();
        selectorArchivo = new javax.swing.JFileChooser();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        detalleMenuItem = new javax.swing.JMenuItem();
        jDialog1 = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        num_insComboBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        num_clusComboBox = new javax.swing.JComboBox();
        aceptarBoton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        ayudaDialog = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        recomendacionesDialog = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        analizarBoton = new javax.swing.JButton();
        resultadoTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        barraCargando = new javax.swing.JProgressBar();
        jPanel3 = new javax.swing.JPanel();
        preprocesarBoton = new javax.swing.JButton();
        numClusters = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        objetosTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        objetosTabla = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        dialogoSelector.setFocusCycleRoot(false);
        dialogoSelector.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        selectorArchivo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        selectorArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorArchivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogoSelectorLayout = new javax.swing.GroupLayout(dialogoSelector.getContentPane());
        dialogoSelector.getContentPane().setLayout(dialogoSelectorLayout);
        dialogoSelectorLayout.setHorizontalGroup(
            dialogoSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(selectorArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
        );
        dialogoSelectorLayout.setVerticalGroup(
            dialogoSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(selectorArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
        );

        dialogoSelector.getAccessibleContext().setAccessibleParent(this);

        detalleMenuItem.setText("Ver Objetos");
        detalleMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalleMenuItemActionPerformed(evt);
            }
        });
        jPopupMenu1.add(detalleMenuItem);

        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jDialog1.setModal(true);

        jLabel6.setText("Seleccione Variables Especiales");

        jLabel7.setText("Numero de instancia");

        jLabel8.setText("Numero de Cluster");

        aceptarBoton.setText("Aceptar");
        aceptarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBotonActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("* Solo las variables a omitir estan diaponibles");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(54, 54, 54)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(num_insComboBox, 0, 220, Short.MAX_VALUE)
                            .addComponent(num_clusComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(aceptarBoton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addGap(31, 31, 31)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(num_insComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(num_clusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(aceptarBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        ayudaDialog.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Cabecera: Se deﬁne el nombre de la relación. \nSu formato es el siguiente:\n@relation <nombre-de-la-relación>\n\nDeclaraciones de atributos: \nEn esta sección se declaran los atributos que compondrán el archivo junto a su tipo. \nLa sintaxis es la siguiente:\n@attribute <nombre-del-atributo> <tipo>\no bien\n@attribute <nombre-del-atributo> {rango}\n\nDonde:\n<nombre-del-atributo> es de tipo string.\n<tipo> acepta diversos tipos, estos son:\n— NUMERIC Expresa números reales.\n— INTEGER Expresa números enteros.\n- El rango sirve para varibles categoricas y se denota:\n{a,b,..}\nSección de datos: Se declaran los datos que componen la relación separando con comas\n los atributos y con saltos de línea las relaciones.\nLa sintaxis es la siguiente:\n\n@data\n4,3.2");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel10.setText("Sintaxis de Weka");

        javax.swing.GroupLayout ayudaDialogLayout = new javax.swing.GroupLayout(ayudaDialog.getContentPane());
        ayudaDialog.getContentPane().setLayout(ayudaDialogLayout);
        ayudaDialogLayout.setHorizontalGroup(
            ayudaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ayudaDialogLayout.createSequentialGroup()
                .addGroup(ayudaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ayudaDialogLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel10))
                    .addGroup(ayudaDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ayudaDialogLayout.setVerticalGroup(
            ayudaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ayudaDialogLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        recomendacionesDialog.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Recomendaciones");

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("Los simbolos \"?\" se convierten automaticamente en 0\n\nEsta aplicacion no acepta atributos tipo Date \n\nun archivo procesado en Weka por \nalgun algoritmo de agrupamiento. \n\nEste software no reconoce rangos, por ejemplo:\n10-20");
        jScrollPane4.setViewportView(jTextArea3);

        javax.swing.GroupLayout recomendacionesDialogLayout = new javax.swing.GroupLayout(recomendacionesDialog.getContentPane());
        recomendacionesDialog.getContentPane().setLayout(recomendacionesDialogLayout);
        recomendacionesDialogLayout.setHorizontalGroup(
            recomendacionesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recomendacionesDialogLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(recomendacionesDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        recomendacionesDialogLayout.setVerticalGroup(
            recomendacionesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recomendacionesDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        analizarBoton.setText("Analizar");
        analizarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizarBotonActionPerformed(evt);
            }
        });

        resultadoTxt.setEditable(false);
        resultadoTxt.setBackground(new java.awt.Color(255, 255, 255));
        resultadoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoTxtActionPerformed(evt);
            }
        });
        resultadoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                resultadoTxtKeyTyped(evt);
            }
        });

        jLabel2.setText("Resultado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(resultadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(barraCargando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(analizarBoton)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barraCargando, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(analizarBoton)
                        .addComponent(resultadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(26, 26, 26))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        preprocesarBoton.setText("Preprocesar");
        preprocesarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preprocesarBotonActionPerformed(evt);
            }
        });

        numClusters.setEditable(false);
        numClusters.setBackground(new java.awt.Color(255, 255, 255));
        numClusters.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numClustersKeyTyped(evt);
            }
        });

        jLabel3.setText("Clusters");

        jLabel4.setText("Objetos");

        objetosTxt.setEditable(false);
        objetosTxt.setBackground(new java.awt.Color(255, 255, 255));
        objetosTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                objetosTxtKeyTyped(evt);
            }
        });

        objetosTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num Cluster", "Num De Objetos"
            }
        ));
        objetosTabla.setComponentPopupMenu(jPopupMenu1);
        objetosTabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                objetosTablaKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(objetosTabla);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(preprocesarBoton)
                .addGap(235, 235, 235))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(42, 42, 42)
                        .addComponent(objetosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel3)
                        .addGap(41, 41, 41)
                        .addComponent(numClusters, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(objetosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(numClusters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(preprocesarBoton)
                .addGap(33, 33, 33))
        );

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setText("Dunn Index");

        jMenu1.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Abrir Archivo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem4.setText("Salir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem2.setText("Sintaxis");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Recomendaciones");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectorArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorArchivoActionPerformed
        String comando = evt.getActionCommand();
        if (comando.equals(JFileChooser.APPROVE_SELECTION)) {
            dialogoSelector.setVisible(false);
            archivoSelecionado = selectorArchivo.getSelectedFile();
            //abrirBoton.setEnabled(true);
            //preprocesarBoton.setEnabled(true);
           // ubicacionTxt.setText(archivoSelecionado.getAbsolutePath());
             try {
            file = new FileReader(archivoSelecionado.getAbsolutePath());
            asin=new Sintactico((new Lexer(file))) ;
            objetos = new ArrayList();
        grupos = new ArrayList();
        preprocesado=new Preprocesado();
        preprocesado=new Preprocesado();
            preprocesarBoton.setEnabled(true);
            analizarBoton.setEnabled(false);
            limpiarTabla(objetosTabla);
            objetosTxt.setText(null);
            numClusters.setText(null);
            resultadoTxt.setText(null);
            JOptionPane.showMessageDialog(this, "Archivo " + archivoSelecionado.getName() + " seleccionado");
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Error al abrir archivo");
        }

        //nombreCargarTxt.setText(archivoSelecionado.getName());
        } else {
            if (comando.equals(JFileChooser.CANCEL_SELECTION)) {
                //abrirBoton.setEnabled(false);
                //JOptionPane.showMessageDialog(null, "selecione un archivo");
                dialogoSelector.setVisible(false);
                preprocesarBoton.setEnabled(false);
            }

        }
    }//GEN-LAST:event_selectorArchivoActionPerformed

    private void preprocesarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preprocesarBotonActionPerformed
        int div, k, clusters, valk, ultimo;
        int var_num_ins,var_num_cluster;
        boolean confirma,orden = false,porcluster=false;
        jDialog1.pack();
        jDialog1.setLocationRelativeTo(null);
        num_instancia=new ArrayList();
        num_cluster=new ArrayList();
        nombreAtributos=new ArrayList();
        try {
            //asin es un objeto de tipo analizador
            Symbol a1 = asin.parse();//esta funcion hace el analisis lexico y sisntactico

        //dataset es el conjunto de datos 
            //data es una lista son los atributos
            
            
            if (asin.action_obj.dataset.size() % asin.action_obj.data.size() == 0) {
            // se divide el numero de datos entre el numero de variables si el residui es 0 hace esto

                //recorre la lista de varibles  la cual contiene una lista por cada variable 
                //data.size devuelve en numero de variables
                //@attribute a {a,b} <--  
                ///          ^---una variable
                for (int i = 0; i < asin.action_obj.data.size(); i++) {

                    //data.get(i).valores obtiene el rango de una variable {a,b}<--esta es la lista que almacena
                    if (!asin.action_obj.data.get(i).getValores().isEmpty()) { //si esta vacia es numerico

                        //numero maximo de posibles valores de un valor nominal {a,b}
                        k = 0;//obitne el tamaño de la lista
                        //el compilador devuelve {b,a} por eso se implenta la varible k

                        for (int j = 0; j < asin.action_obj.data.get(i).getValores().size(); j++) {
                            //remplazar requiere los datos es decir dataset
                            //
                            preprocesado.buscar_remplazar(asin.action_obj.dataset, asin.action_obj.data.get(i).getValor(j), i, asin.action_obj.data.size(), String.valueOf(k));
                            k++;
                        }
                    }
                }

                div = asin.action_obj.dataset.size() / asin.action_obj.data.size();
                //se divide el numero de datos entre el numero de variables es decir 44 / 4
                //                                              numero de datos    --^    ^---numero de variables     
                //obtiene una variable
                //un archivo procesado en weka al guardar el agrupamiento la ultima variable corresponde al cluster al que pertenece
                //@attribute Cluster{Cluster0,Cluster1}

              //  if (!asin.action_obj.data.get(asin.action_obj.data.size() - 1).getValores().isEmpty()) {//<---no deberia estar limpia no sabriamos cual cluster es cual
                    ///                  ^-----obtiene una varible ^---en la posicion final se manda el tamaño - 1 por que las posiciones enpiezan en 0
                    //clusters = asin.action_obj.data.get(asin.action_obj.data.size() - 1).getValores().size();//<-- se obtiene la cantidad de valores de una variable
                    //obtiene cual es el numero de clusters que se encuentra en la posicion 3 de data pero size es 4 por eso le restamos uno
                    confirma = false;
                    for (int i = 0; i < asin.action_obj.data.size(); i++) {
                        //es una funcion que permite saber los datos pertenecen a la varible que represntan
                        //si todos los datos del dataset son numeros y en caso de que en la busqueda no haya sido remplzado por que nos estaba en el rango
                        //se manada si la variable era numerica(sin rango,es vacia) o categorica(con rango,tiene aalgo) 
                        //i es positcion es la cual esta el dato
                        //el data.size es para solo analice la columna de datos numericos o categoricos a la cual peretenece la variable
                        confirma = preprocesado.confirma(asin.action_obj.dataset, asin.action_obj.data.get(i).getValores().isEmpty(), i, asin.action_obj.data.size());
                        //devuelve una falso si encontro una incongruencia
                        if (!confirma) {
                            break;
                            //permite salir del ciclo si hay datos erroneso
                        }
                    }

                    //System.out.println(confirma);
                    if (confirma) {// si es verdad 
                        //convierte los datos que son cadenas a Doubles
                        // div de objetos
                        // data.size es el salto parte 1,2,3,4,5,6 en numero de variables para el caso de 4
                        //1,2,3,cluster0 <--contiene las varibles del objeto 1
                        //4,5,6,cluster1 <--objeto 2
                        // ^ esto es datos 

                        objetos = preprocesado.genera(asin.action_obj.dataset, div, asin.action_obj.data.size());
                        
                        
                        //num_ins regresa falso o verdadero si se puso expliciamente el numero de instancia
                        //num_ins = asin.action_obj.num_ins;
                        
                        for (int i = 0; i < asin.action_obj.data.size(); i++) {
                                nombreAtributos.add(asin.action_obj.data.get(i).getNombre());

                            if (preprocesado.busca_indices(objetos,i)) {
                              num_insComboBox.addItem(asin.action_obj.data.get(i).getNombre());///modificar
                             // num_instancia.add(i);
                              orden = true;
                            }else{
                                num_clusComboBox.addItem(asin.action_obj.data.get(i).getNombre());
                                porcluster=true;
                                
                            //num_cluster.add(i);
                            }                            
                            
                        }   
                            if(!orden){
                            num_insComboBox.setEnabled(false);
                            }
                            if( porcluster){
                            preprocesado.buscar(nombreAtributos, (String) num_insComboBox.getSelectedItem());
                            jDialog1.setVisible(true);
                              int buscarclus = preprocesado.buscar(nombreAtributos, (String) num_clusComboBox.getSelectedItem());
                            int buscarins= preprocesado.buscar(nombreAtributos, (String) num_insComboBox.getSelectedItem());
                            
                            if(asin.action_obj.data.get(buscarclus).getValores().isEmpty())
                                {
                                    asin.action_obj.data.get(buscarclus).setValores(
                                        preprocesado.rango_clusternum(objetos, buscarclus));
                                    objetos=preprocesado.busca(objetos, asin.action_obj.data.get(buscarclus).getValores(), buscarclus);
                                    
                                    //  preprocesado.rango_clusternum(objetos, buscarclus);
                                }
                            
                            clusters = asin.action_obj.data.get(buscarclus).getValores().size();
                            for (int i = 0; i < clusters; i++) {//un bucle hasta el nuemro de clusters en este caso 2 
                                grupos.add(new Grupo()); //lista la cual contine los grupos                         ^ -- por lo tanto se crean 2 grupos
                                //recordemoss que el {a,b} a es remplazada por 1 y b por 2
                                for (int j = 0; j < objetos.size(); j++) {//un clico que se detine hasta el nuemro de objetos

                                    //se obtiene la ultima posicion contiene a que cluster pertenece y se compara 
                                   // System.out.println(objetos.get(j).getAtributo(buscarclus)+"+"+valk);
                                    if ((objetos.get(j).getAtributo(buscarclus)) == i) {
                                        //si es verdad se agrega el objeto es la posicion j ese cluster a la lista

                                        grupos.get(i).agregarObjeto(objetos.get(j));
                                        // ^-- el numero del grupo ^---objetos en la posicion j
                                    }

                                }
                            }
                           
                            
                            //ultimo = objetos.get(0).getNumAtributos() - 1;
                          
                            nombreAtributos.remove(buscarclus);
                            if (orden) {
                            nombreAtributos.remove(buscarins);
                            }
                            //System.out.println(buscarclus);
                            for (int i = 0; i < clusters; i++) {
                                //funcion sirve para eliminar el ultimo valor que nos dice a que cluster pertenece no sirve para el calculo del indice
                                preprocesado.eliminarPosicion(grupos.get(i).getObjetos(), buscarclus);
                                if (orden) {
                                    
                                    preprocesado.eliminarPosicion(grupos.get(i).getObjetos(),buscarins);
                                    
                                }
                            }
 /*for (int j = 0; j < grupos.size(); j++) {
                            for (int i = 0; i < grupos.get(j).getObjetos().size(); i++) {
                        preprocesado.imprimed(grupos.get(j).getObjetos().get(i).getAtributos());    
                            System.out.println("");
                        }
                        }*/
                            numClusters.setText(Integer.toString(grupos.size()));//coloca el numro de clusters en cuadro de texto
                            objetosTxt.setText(Integer.toString(div));
                            analizarBoton.setEnabled(true);
                            //System.out.println(grupos.get(0).getObjeto(0).getAtributos());
                            for (int i = 0; i < grupos.size(); i++) {
                                datos[0] = i + 1;//numero del cluster
                                datos[1] = grupos.get(i).getObjetos().size(); //numero de objetos que tiene el cluster
                                modelo.addRow(datos);   // añade una fila con los datos de arreglo
                            }
                            JOptionPane.showMessageDialog(null, "Se cargaron " + div + "objetos");
                            analizarBoton.setEnabled(true);
                        } else {
                    JOptionPane.showMessageDialog(null, "Este Archivo no esta clasificado por cluster");

                }
                    }
                /*} else {
                    JOptionPane.showMessageDialog(null, "Este Archivo no esta clasificado por cluster");

                }*/
            } else {
                JOptionPane.showMessageDialog(null, "falta una variable");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error en el archivo"+ex.getMessage());
        }           
         /* file = null;
        asin = null;*/
        asin.action_obj.num_var = 0;
        asin.action_obj.data = null;
        asin.action_obj.dataset = null;
        objetos = null;
        //grupos = null;
        preprocesado=null;
        num_clusComboBox.removeAllItems();
                            num_insComboBox.removeAllItems();
                        num_cluster=null;
                       num_instancia=null;
       preprocesarBoton.setEnabled(false);
       
        
       
    }//GEN-LAST:event_preprocesarBotonActionPerformed

    private void analizarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizarBotonActionPerformed
        // TODO add your handling code here
        analizarBoton.setEnabled(false);
        DunnHilo procesodunn=new DunnHilo(grupos,resultadoTxt);
        CargandoThread cargandohilo=new CargandoThread(barraCargando);
        proceso=new Thread(procesodunn);
        cargando=new Thread(cargandohilo);
        proceso.start();
        cargando.start();
     /*   CSIndex indice=new CSIndex();
    double arriba = indice.sumCk(grupos);
        System.out.println(arriba);
       */ 
    }//GEN-LAST:event_analizarBotonActionPerformed

    private void objetosTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_objetosTxtKeyTyped
       evt.consume();
    }//GEN-LAST:event_objetosTxtKeyTyped

    private void numClustersKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numClustersKeyTyped
      evt.consume();
    }//GEN-LAST:event_numClustersKeyTyped

    private void resultadoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resultadoTxtKeyTyped
evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoTxtKeyTyped

    private void objetosTablaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_objetosTablaKeyTyped
        // TODO add your handling code here:
        evt.consume();
    }//GEN-LAST:event_objetosTablaKeyTyped

    private void resultadoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoTxtActionPerformed

    private void detalleMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalleMenuItemActionPerformed
        // TODO add your handling code here:
         if (objetosTabla.getSelectedRow() != -1) {
        detalle.setLocationRelativeTo(this);
        detalle.llena(grupos.get(objetosTabla.getSelectedRow()).getObjetos(),nombreAtributos);
        detalle.setVisible(true);
        
         }
    }//GEN-LAST:event_detalleMenuItemActionPerformed

    private void aceptarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBotonActionPerformed
        jDialog1.setVisible(false);
    }//GEN-LAST:event_aceptarBotonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      dialogoSelector.pack();
      dialogoSelector.setLocationRelativeTo(this);
      dialogoSelector.setVisible(true);//selectorvn.setf
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        ayudaDialog.pack();
        ayudaDialog.setLocationRelativeTo(this);
        ayudaDialog.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        recomendacionesDialog.pack();
        recomendacionesDialog.setLocationRelativeTo(this);
        recomendacionesDialog.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
    
        //this.setVisible(false);
        System.exit(1); 
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dunn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dunn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dunn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dunn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dunn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarBoton;
    private javax.swing.JButton analizarBoton;
    private javax.swing.JDialog ayudaDialog;
    private javax.swing.JProgressBar barraCargando;
    private javax.swing.JMenuItem detalleMenuItem;
    private javax.swing.JDialog dialogoSelector;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField numClusters;
    private javax.swing.JComboBox num_clusComboBox;
    private javax.swing.JComboBox num_insComboBox;
    private javax.swing.JTable objetosTabla;
    private javax.swing.JTextField objetosTxt;
    private javax.swing.JButton preprocesarBoton;
    private javax.swing.JDialog recomendacionesDialog;
    private javax.swing.JTextField resultadoTxt;
    private javax.swing.JFileChooser selectorArchivo;
    // End of variables declaration//GEN-END:variables
}
