
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package dunn;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int comilla = 15;
  public static final int p_integer = 3;
  public static final int cadena = 16;
  public static final int coma = 9;
  public static final int numero = 18;
  public static final int comilla_doble = 17;
  public static final int numeric = 2;
  public static final int p_date = 4;
  public static final int p_relation = 7;
  public static final int p_data = 6;
  public static final int p_attribute = 8;
  public static final int abrep = 10;
  public static final int punto = 13;
  public static final int EOF = 0;
  public static final int palabra = 19;
  public static final int error = 1;
  public static final int p_string = 5;
  public static final int interrogacion = 14;
  public static final int p_real = 12;
  public static final int cierrap = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "numeric",
  "p_integer",
  "p_date",
  "p_string",
  "p_data",
  "p_relation",
  "p_attribute",
  "coma",
  "abrep",
  "cierrap",
  "p_real",
  "punto",
  "interrogacion",
  "comilla",
  "cadena",
  "comilla_doble",
  "numero",
  "palabra"
  };
}

