/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dunn;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 05C4R
 */
public class VisualizaObjetos extends javax.swing.JDialog {
DefaultTableModel modelo;
Object datos[];

    /**
     * Creates new form VisualizaObjetos
     * @param parent
     * @param modal
     */
    public VisualizaObjetos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         
         
    }
    public void limpiarTabla(JTable tabla){
        try {
            DefaultTableModel modelo=(DefaultTableModel) tabla.getModel();
            int filas=tabla.getRowCount();
            int col=tabla.getColumnCount();
            for (int i = 0;filas>i; i++) {
                modelo.removeRow(0);
            }
            for (int i = 0;col>i; i++) {
                tabla.getColumnModel().removeColumn(tabla.getColumnModel().getColumn(0));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }
    }
    
    public void llena(ArrayList<Objeto> objetos,ArrayList<String> nombrevaribles) {
       modelo = (DefaultTableModel)detalleTabla.getModel();
         detalleTabla.setModel(modelo);
        modelo.addColumn("Num Objeto");
        for (int i = 0; i < nombrevaribles.size(); i++) {
            modelo.addColumn(nombrevaribles.get(i));
        }
        /*modelo.addColumn(1);
        modelo.addColumn(2);
        modelo.addColumn(3);
*/        datos = new Object[objetos.get(0).getAtributos().size()+1];
        for (int i = 0; i < objetos.size(); i++) {
            datos[0]=i+1;
            
            for (int j = 0; j <objetos.get(0).getAtributos().size(); j++) {
                datos[j+1]=objetos.get(i).getAtributo(j);
                               
            }
            modelo.addRow(datos);   // añade una fila con los datos de arreglo
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        detalleTabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        detalleTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        detalleTabla.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(detalleTabla);
        detalleTabla.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        //limpiarTabla(detalleTabla);
        modelo = new DefaultTableModel();
detalleTabla.setModel(modelo);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable detalleTabla;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
